### ISSUE TITLE
How many episodes from the HM3D dataset did you use for testing?

### ISSUE THREAD

**Issue by zhai-create** [LYX0501/InstructNav#10]
I would like to confirm how many episodes from "HM3D-v2.val" you used for testing. Is the number of test episodes set to 500 in the code?

**Comment by LYX0501** [comment]
Our standard evaluation is based on 2000 test episodes. The 500 setting in the code is just to prevent users from exhausting their GPT API token quota.

**Comment by LYX0501** [comment]
Our standard evaluation is based on 1000 test episodes from HM3D V0.2 Val. 

The 500 setting in the code is just to prevent users from exhausting their GPT API token quota.
