### ISSUE TITLE
What is your success distance on object goal task? 

### ISSUE THREAD

**Issue by zhai-create** [LYX0501/InstructNav#11]
I would like to confirm what is the success distance during object goal task testing? I noticed that the comparison algorithms all used a success distance of 1m, but in your code, you used a success distance of 0.25m.

**Comment by zhai-create** [comment]
Meanwhile, I noticed that "HM3D-v0.2-val" only has 1000 episodes, and when 'args. eval_ episodes' is set to 2000, the following error occurs:
![报错](https://github.com/user-attachments/assets/64ed95c1-81a4-4883-8446-4a3585b0e52e)
Does this mean I can't use 2000 test episodes?

**Comment by LYX0501** [comment]
Hi Shichao, sorry for mistakenly remembering. If you wish to reproduce our work, please set args.eval episodes to 1000 and the success distance to 1.0m based on the HM3D V0.2 Val.
