### ISSUE TITLE
Real robot？

### ISSUE THREAD

**Issue by helloiee** [LYX0501/InstructNav#2]
Can this be deployed on a real robot for navigation?

**Comment by LYX0501** [comment]
Yes, we have validated the InstructNav method on the Turtlebot 4. 

We obtain color and depth images through an RGBD camera and acquire poses from the SLAM Toolbox, enabling real-time scene reconstruction. Once InstructNav predicts the next waypoint, point-to-point path planning can be achieved through Navigation2. The Turtlebot 4, SLAM Toolbox, and Navigation 2 we used are all open source, making it easy for researchers to replicate.

**Comment by kk6398** [comment]
> Yes, we have validated the InstructNav method on the Turtlebot 4.
> 
> We obtain color and depth images through an RGBD camera and acquire poses from the SLAM Toolbox, enabling real-time scene reconstruction. Once InstructNav predicts the next waypoint, point-to-point path planning can be achieved through Navigation2. The Turtlebot 4, SLAM Toolbox, and Navigation 2 we used are all open source, making it easy for researchers to replicate.

In the paper, you mentioned that choosing 6 viewpoints can achieve the best results. In Real Robot Experiments, does the robot need to stop at each time step to take images from 6 viewpoints for analysis? Will this reduce efficiency?

**Comment by LYX0501** [comment]
Not every time step but every decision step.
