### ISSUE TITLE
habitat and dataset issue

### ISSUE THREAD

**Issue by kunhumllop** [LYX0501/InstructNav#3]
Thank you for the impressive work on this project. I would love to replicate your work
I have installed the 0.3.1 version of habitat and habitat_lab, can I ask if the habitat-baselines of the habitat_lab need to be installed as well. And I would like to ask if the scenes of the HM3D dataset are just validation sets.
Thank you!

**Comment by wzcai99** [comment]
Hi, thank you for your interest in our work. It is not necessary to install the habitat-baseline and yes, the dataset we use is the Val set.
