### ISSUE TITLE
HM3D val split runtime

### ISSUE THREAD

**Issue by alomrani** [LYX0501/InstructNav#4]
Hi,

Thanks for open sourcing this work. How long does it take to run on the Val split? It currently takes more than 30 min per episode for me.

Thanks,
Mohammad

**Comment by zhouak47** [comment]
Hi, i meet some trouble when dealing with the dataset.I do not know which data in hm3d dataset should i download. Could you tell me which data in hm3d dataset should i download and how to organize and place the data?Thanks a lot

**Comment by wzcai99** [comment]
@alomrani I think the running speed depends on the API calling time. You can check the GPT4 and GPT4V calling time.

**Comment by wzcai99** [comment]
@zhouak47 Download both episode data and scene data. Scene Data: https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#habitat-matterport-3d-research-dataset-hm3d, Episode Data: https://dl.fbaipublicfiles.com/habitat/data/datasets/objectnav/hm3d/v2/objectnav_hm3d_v2.zip

**Comment by zhouak47** [comment]
thanks for your kind reply
