### ISSUE TITLE
How to run this project for VLN-CE task?

### ISSUE THREAD

**Issue by chenguanqi** [LYX0501/InstructNav#6]
VLN-CE uses [Habitat-Sim](https://github.com/facebookresearch/habitat-sim/tree/v0.1.7) 0.1.7, while this project is based on habitat-sim v0.3.1. Could you give me some advice on how to run this project for the VLN-CE task?

**Comment by LYX0501** [comment]
In the [config_utils.py](https://github.com/LYX0501/InstructNav/blob/main/config_utils.py), we have provided r2r_config. After you have specified your VLN-CE dataset path, you can set up the VLN-CE environment by 
```
habitat_config = r2r_config(stage='val_unseen')
env = habitat.Env(habitat_config)
```

We also plan to open source InstructNav codes on the VLN-CE task later. Welcome to star our project!

**Comment by chenguanqi** [comment]
Thanks for your reply.
So, we can directly run this project to perform the VLN-CE task on habitat-sim v0.3.1, right?
