### ISSUE TITLE
 problem with the data set

### ISSUE THREAD

**Issue by kunhumllop** [LYX0501/InstructNav#7]
Dear author, I am very interested in your work. During the reproduction process:[22:06:29:432985]:[Error]:[Scene] SemanticScene.cpp(137)::loadSemanticSceneDescriptor : SSD Load Failure! File with SemanticAttributes-provided name `/home/kunkun/InstN/dataset/scenes/hm3d_v0.2/val/00829-QaLdnwvtxbs/QaLdnwvtxbs.basis.scn` exists but failed to load.
2024-10-14 22:06:30,062 Initializing task ObjectNav-v1
 I encountered the following problems. I think it may be a problem with the data set. Can I have a look at your specific data set directory? I look forward to your reply. reply.

1(https://github.com/user-attachments/assets/8cb6244b-7652-4361-aa5e-d171fcf4a03d)

**Comment by LiUziYu07** [comment]
I’ve encountered the same issue. Have you found a solution?

**Comment by LiUziYu07** [comment]
I’ve encountered the same issue. Have you found a solution?

**Comment by LYX0501** [comment]
In the definition file of habitat.Env, you may find codes like
```
self._config.simulator.scene_dataset = (
    self.current_episode.scene_dataset_config
)
```
You can comment them out and then try running again.

**Comment by LiUziYu07** [comment]
It 

> In the definition file of habitat.Env, you may find codes like
> 
> ```
> self._config.simulator.scene_dataset = (
>     self.current_episode.scene_dataset_config
> )
> ```
> 
> You can comment them out and then try running again.

It works. Thanks for your help.
